### ISSUE TITLE
Manifest internatialization

### ISSUE THREAD

**Issue by husayt** [nuxt-community/i18n-module#699]
### Is your feature request related to a problem? Please describe.
The only thing I couldn't do is internationalise manifests

### Describe the solution you'd like
Google gives a nice solution here:
https://developer.chrome.com/webstore/i18n

### Additional context
This will give complete i18n package for modern apps

**Comment by rchl** [comment]
- What kind of manifest are we talking about? Chrome Extensions manifests? Are you using `nuxt-i18n` in a Chrome extension?
 - Can you link to a specific manifest specification that you are thinking about?
 - Also, are those fully static and can be generated at build time?
 - It's not clear to me what would be the role of `nuxt-i18n` here.

**Comment by rchl** [comment]
Closing due to no response.
