### ISSUE TITLE
Reactivity broken after redirecting from a plugin (nuxt generate)

### ISSUE THREAD

**Issue by SherifGhoz** [nuxt-community/i18n-module#737]
Hello, 

after redirection happens, the page is translated successfully, but the head content doesn't change (title, meta description ... etc)

the problem is only when using nuxt generate (using Netlify).

Locally, it works, title changes.

reproduce the issue:
1- open website from a browser with default language french:
https://tender-raman-68344c.netlify.app/

2- the url will be (`https://tender-raman-68344c.netlify.app/fr`) and the body content will be ("francais") till now everything is ok...  but page title remains ("english") :disappointed: 

code is here:
https://codesandbox.io/s/github/SherifGhoz/redirection-issue
https://github.com/SherifGhoz/redirection-issue

Is there any solution ?

**Comment by rchl** [comment]
Please create repro test case. Got example on codesandbox

**Comment by SherifGhoz** [comment]
> Please create repro test case. For example on codesandbox

done

**Comment by rchl** [comment]
Thanks. I can reproduce.

It does look like a core Nuxt issue though. I can probably manage to reproduce it without nuxt-i18n. Something to do with redirecting page early during loading.

**Comment by rchl** [comment]
I should be able to fix it though.

**Comment by simplenotezy** [comment]
This does not only happen with page title; it also happens in other places (e.g. the menu). See example: https://thejewelleryroom.com - try to get your locale to be "danish", you should be redirected to https://thejewelleryroom.com/da but page content is still english, and so is the menu.

**Comment by simplenotezy** [comment]
Could you recommend any workaround @rchl untill this is fixed?

**Comment by rchl** [comment]
I'm looking into it.

**Comment by rchl** [comment]
@simplenotezy Are you able to beta test the fix for me?
`npm i nuxt-i18n@beta`
or
`yarn add nuxt-i18n@beta`

It has some potential to change behavior as it uses `location.assign()` to redirect instead of using router to push the route.
Fix only affects static mode on the client.

**Comment by simplenotezy** [comment]
On it

**Comment by simplenotezy** [comment]
Seems to do the trick, see https://thejewelleryroom.com

However, I just found this bug: https://github.com/nuxt-community/nuxt-i18n/issues/717

**Comment by bpeab** [comment]
The work-around seems find once the website is generated but still doesn't work on development mode (with the dev server).

**Comment by rchl** [comment]
The fix was released and #717 is hopefully also addressed so closing this one.
