### ISSUE TITLE
[Feature Request] Add dir attribute for each locale

### ISSUE THREAD

**Issue by HapLifeMan** [nuxt-community/i18n-module#762]
### Is your feature request related to a problem? Please describe.
I'm using this package to translate my app, and now I'm adding an RTL locale.
It would be great if nuxt-i18n could manage the body dir attribute.

### Describe the solution you'd like
I propose to add a `dir` property for each locale in the module (values would be `rtl`, `ltr` or `auto` [by default](https://developer.mozilla.org/fr/docs/Web/HTML/Attributs_universels/dir)). For example:

```js
// nuxt.config.js, inside nuxt-i18n module

locales: [
  { code: 'ar', iso: 'ar', file: 'ar/app.js', dir: 'rtl' },
  { code: 'en', iso: 'en-US', file: 'en/app.js', dir: 'ltr' },
  { code: 'fr', iso: 'fr-FR', file: 'fr/app.js', dir: 'ltr' },
],
```

Then this would be added in the HTML by setting a new `dir` attribute at a very top level of the document, for example in the `<html>` or `<body>` tag. I think it's a mandatory feature for an i18n repo 😊

### Describe alternatives you've considered
As for now I'm using a custom plugin and adding the dir property as soon as I can:

```js
// plugins/ltr-rtl.js

export default function({ app }, inject) {
  const dir = () => app.i18n.locales.find((x) => x.code === app.i18n.locale)?.dir;
  inject( 'dir', dir);
}
```

```vue
<!-- layouts/default.vue -->

<div id="app" :dir="$dir()">
  My app here...
</div>
```

What do you think? 😊

**Comment by majdal** [comment]
RTL always has so little support, so I'm happy to see it being brought up! 

I have a similar issue that I'm trying to resolve. I tried two different solutions, and both are unsatisfactory. I'm still fairly new to Nuxt, so I'm not 100% sure this is the right approach. It would be good to create a more "standard" way of solving the rtl problem.

```js
export default function({ app }) {
  // beforeLanguageSwitch called right before setting a new locale
  app.i18n.beforeLanguageSwitch = (oldLocale, newLocale) => {
    app.head.htmlAttrs = {
      lang: newLocale,
      dir: newLocale == "ar" ? "rtl" : "ltr"
    }
  }
}
  ```
Nevertheless, it would be great to have a `$dir` property to use where needed.

**Comment by HapLifeMan** [comment]
Hey @rch, I would really love to have your opinion 😊

**Comment by rchl** [comment]
Great idea and should be easy to do. :)

**Comment by glenpike** [comment]
You can also target the direction CSS property as a workaround - https://developer.mozilla.org/en-US/docs/Web/CSS/direction
e.g.
```
html[lang="ar-SA"] {
  direction: rtl;
}
```

**Comment by HapLifeMan** [comment]
@glenpike Using the HTML attribute is way much better than the CSS property 😊

**Comment by glenpike** [comment]
> @glenpike Using the HTML attribute is way much better than the CSS property 😊

Hi, yes, sorry, should have commented this was a workaround.

**Comment by HapLifeMan** [comment]
Hi @rchl, any news on this feature request? 😊

**Comment by francisceril** [comment]
Is the feature already added?

**Comment by iifawzi** [comment]
We can leverage from the SEO mode when enabled,  it already adds the ISO to the HTML so it will be so easy to do add the dir, or you intend to make it a stand-alone feature?

**Comment by iifawzi** [comment]
Hi,  i'm trying to make this done, as i notice, we need to combine both the meta which coming when the seo-mode is enabled and the dir attribute that will be coming from the `dir` when be implemented - in the httmlattrs, is it the best approach? any ideas?

**Comment by rchl** [comment]
Resolved through #1023 and released in https://github.com/nuxt-community/i18n-module/releases/tag/v6.19.0.

See the `dir` property in https://i18n.nuxtjs.org/options-reference#locales

**Comment by aliwesome** [comment]
@rchl How can we get that property in pages or components?

**Comment by rchl** [comment]
@aliwesome not sure what you mean exactly but you need to add this in the default layout or individual pages:

```js
export default {
  head () {
    return this.$nuxtI18nHead()
  }
}
```

**Comment by Mo7ammedMamdou7** [comment]
I made this solution and worked fine:
First, create 'localize.js' as a plugin file in the plugins folder and add this code :
```
export default ({ app }) => {
  app.router.afterEach((to, from) => {
    if (app.i18n.locale === 'ar') {
      app.head.htmlAttrs.dir = 'rtl'
      app.head.htmlAttrs.lang = 'ar'
    } else {
      app.head.htmlAttrs.dir = 'ltr'
      app.head.htmlAttrs.lang = 'en'
    }
  })
}
```
This file will be imported to the nuxt.config.js file :
```
plugins: [
    '~/plugins/localize.js',
  ],
```
Then, Go to your nav component file and add this head function in your script to handle route changes:
```
head() {
    if (this.$i18n.locale === 'ar') {
      return {
        htmlAttrs: {
          lang: 'ar',
          dir: 'rtl',
        },
      }
    } else {
      return {
        htmlAttrs: {
          lang: 'en',
          dir: 'ltr',
        },
      }
    }
  },
```

**Comment by iifawzi** [comment]
@Mo7ammedMamdou7
it's now supported out of the box.
https://i18n.nuxtjs.org/options-reference/#locales
Ref: https://github.com/nuxt-community/i18n-module/pull/1023

**Comment by Mo7ammedMamdou7** [comment]
> @Mo7ammedMamdou7 it's now supported out of the box. https://i18n.nuxtjs.org/options-reference/#locales Ref: #1023

Yes, bro thanks a lot for your support,
This is the configuration I made and worked fine:
First, I add this code to the i18n config in the nuxt.config.js file:
```
locales: [
      {
        code: 'ar',
        name: 'Arabic',
        iso: 'ar-UAE',
        file: 'ar.js',
        dir: 'rtl',
      },
      {
        code: 'en',
        name: 'English',
        iso: 'en-US',
        file: 'en.js',
        dir: 'ltr',
      },
    ],
```
Then I added this code to default.vue layout file:
```
head() {
    return this.$nuxtI18nHead({ addDirAttribute: true, addSeoAttributes: true })
  },
```

**Comment by AmirrezaJM** [comment]
I wrote it on nuxt3(vue3) but I can't switch between dir and lang for each locale 
How I should fix it? 
my default.vue layout file :
```
const head = useLocaleHead({
  addDirAttribute: true,
  addSeoAttributes: true
})

useHead({
  htmlAttrs: {
    lang: head.value.htmlAttrs!.lang,
    dir: head.value.htmlAttrs!.dir
  },
})


my i18n config in nuxt.cofing.ts file: 
```
    i18n: {
        locales: [
            {
                code: 'fa',
                iso: 'fa-IR',
                name: 'Farsi',
                file: 'fa-IR.json',
                dir: 'rtl',
            },
            {
                code: 'en',
                iso: 'en-US',
                name: 'English',
                file: 'en-US.json',
                dir: 'ltr',
            },
        ],
        defaultLocale: 'fa',
        detectBrowserLanguage: false,
        langDir: "lang",
         // & add `vueI18n` option to `@nuxtjs/i18n` module options
        vueI18n: {
            legacy: false,
            fallbackLocale: 'fa',
        }
    }

**Comment by momurad18** [comment]
> useLocaleHead

you need to add this to your layout 

`<Html :lang="head.htmlAttrs.lang" :dir="head.htmlAttrs.dir">your template</Html>`
