### ISSUE TITLE
Route alias support

### ISSUE THREAD

**Issue by obaidsamadian** [nuxt-community/i18n-module#772]
I've installed `router-extras-module`. When I create an `alias` for a route, the `nuxt-i18n` doesn't recognize the `aliases`, I mean when I checked the `router.js` file inside of `.nuxt` folder. I saw the following code. How can I fix this?

here's the screenshot of the `alias` I've created:
![Screen Shot 2020-06-24 at 10 32 12 AM](https://user-images.githubusercontent.com/9816876/85506772-3eed0080-b606-11ea-89fe-8fc358804a18.png)

and here's the generated `routes` inside of `.nuxt/router.js` file:
 ```
routes: [{
    path: "/pl",
    component: _564d4845,
    alias: ["/search/:query"],
    name: "search___pl"
  }, {
    path: "/pl",
    component: _cb5cf9b0,
    name: "index___pl"
  }, {
    path: "/pl/new-offer/:id",
    component: _505b757a,
    name: "edit-property___pl"
  }, {
    path: "/pl/rooms/:id",
    component: _d072ccf0,
    alias: ["/:city/rooms/:id"],
    name: "rooms___pl"
  }, {
    path: "/new-offer/:id",
    component: _505b757a,
    name: "edit-property___en"
  }, {
    path: "/rooms/:id",
    component: _d072ccf0,
    alias: ["/:city/rooms/:id"],
    name: "rooms___en"
  }, {
    path: "/",
    component: _564d4845,
    alias: ["/search/:query"],
    name: "search___en"
  }, {
    path: "/",
    component: _cb5cf9b0,
    name: "index___en"
  }]
```

**Comment by rchl** [comment]
I'm not sure how this should be handled.

I could prefix aliases the same way as I'm prefixing the path but then someone would probably say that they want their aliases to be untouched (maybe someone wants to have an alias in a locale name, without the prefix).

Of course, it could be an optional feature but I have aversion to adding new options as that logarithmically increases the number of combinations of settings that are possible and should be tested.

**Comment by hmaesta** [comment]
Maybe [router-extras-module](https://github.com/nuxt-community/router-extras-module#define-multiple-aliases-for-single-page) can help.
