### ISSUE TITLE
How to change default lang to ( '/' or '/fr' )?

### ISSUE THREAD

**Issue by fahamidev** [nuxt-community/i18n-module#778]
Hi everyone.

### What is the problem?
When I set `defaultLocale` to `/` or `/fr` and call the domain without prefix. Inside `nuxtServerInit` returns the `route.path`  `/en` instead of `/fr` or `/`.

### What packages have been used?
**package.json**:
```{
  "dependencies": {
    "nuxt": "^2.0.0",
    "nuxt-i18n": "^6.2.1",
     .....
  },
  "devDependencies": {
    "@nuxtjs/vuetify": "^1.9.0",
     .....
  }
}
```

### Configs in nuxt.config.js:
```
modules: [
......
            [
                'nuxt-i18n', {
                    locales: [{
                        "name": "Arabic",
                        "code": "ar",
                        "iso": "ar-AR",
                        "file": "ar.js"
                    },{
                        "name": "English",
                        "code": "en",
                        "iso": "en-US",
                        "file": "en.js"
                    },
                    {
                        "name": "Franch",
                        "code": "fr",
                        "iso": "ft-FR",
                        "file": "fr.js"
                    },
                    ],
                    detectBrowserLanguage: {
                        useCookie: false,
                        fallbackLocale: 'fr',
                        cookieKey: 'route_path',
                        locale: 'fr',
                        alwaysRedirect: true,
                    },
                    baseUrl: '/',
                    strategy: 'prefix',
                    lazy: true,
                    langDir: 'locales/', 
                    defaultLocale: 'fr',
                    vueI18n: {
                        locale: 'fr',
                        fallbackLocale: 'fr',
                    },
                }
            ], 
        ],
```

### Some codes in `nuxtServerIniti`:
```export const actions = {
    async nuxtServerInit({ state, commit, dispatch }, { route, app }) {
         // let arr = locales.....
          if(route.path == '/' || app.i18n.locale == '/' || route.path == '/sp' ||  app.i18n.locale == '/sp' ) {
                return redirect(app.localePath('index', defaultLocale))
         }
 }
}
```

### What approach is expected?
When user enter domain without **prefix** in the address bar such as `domain.com/`, return `route.path` => ( `/fr` or `/`)

**Comment by rchl** [comment]
Why are you manually trying to redirect from the root path? Is `rootRedirect` option not working for you?

BTW. This `app.i18n.locale == '/'` doesn't make sense. `locale` is a language code.

Also, it might be fine but you don't have to set `vueI18n.locale` and also `detectBrowserLanguage.locale` is not a valid option.

**Comment by fahamidev** [comment]
> Why are you manually trying to redirect from the root path? Is `rootRedirect` option not working for you?
> 
> BTW. This `app.i18n.locale == '/'` doesn't make sense. `locale` is a language code.
> 
> Also, it might be fine but you don't have to set `vueI18n.locale` and also `detectBrowserLanguage.locale` is not a valid option.

@rchl Thank you for your guidance.

**Now my code is like this in nuxt.config.js**:
```
[
                'nuxt-i18n', {
                    // async axios.get().then((res) => res.locales)
                    locales: [
                        { "name": "Arabic", "code": "ar", "iso": "ar-AR", "file": "ar.js" },
                        { "name": "English", "code": "en", "iso": "en-US", "file": "en.js" },
                        { "name": "Franch", "code": "fr", "iso": "ft-FR", "file": "fr.js" },
                    ],
                    detectBrowserLanguage: {
                        useCookie: true,
                        fallbackLocale: 'fr',
                    },
                    baseUrl: '/',
                    strategy: 'prefix',
                    lazy: true,
                    langDir: 'locales/',
                    defaultLocale: '/fr',
                    vueI18n: {
                        locale: 'fr',
                        fallbackLocale: 'fr',
                    },
                }
            ], 
```
Why does it always return `/en`  when the language(`locale`) is not entered in the URL? (ex: `domain.com`)
How can I change locale to `/fr` when the language(`locale`) is not entered in the URL?

**Comment by rchl** [comment]
> Why does it always return /en when the language(locale) is not entered in the URL?

Because your browser-preferred locale is english, I presume.

> How can I change locale to /fr when the language(locale) is not entered in the URL?

I've said already - `rootRedirect` option.

**Comment by fahamidev** [comment]
Now my code in `nuxt.config.js`:
```
[
                'nuxt-i18n', {
                    locales: [
                        { "name": "Arabic", "code": "ar", "iso": "ar-AR", "file": "ar.js" },
                        { "name": "English", "code": "en", "iso": "en-US", "file": "en.js" },
                        { "name": "Franch", "code": "fr", "iso": "ft-FR", "file": "fr.js" },
                    ],
                    detectBrowserLanguage: false,
                    baseUrl: '/',
                    strategy: 'prefix',
                    lazy: true,
                    langDir: 'locales/',
                    defaultLocale: 'fr',
                    vueI18n: {
                        locale: 'fr',
                        fallbackLocale: 'fr',
                    },
                    rootRedirect: 'fr'
                }
            ],
```

and my log in `nuxtServerInit`:
`console.log('app.i18n.locale ', app.i18n.locale)`

This code works inside my computer console in development mode but does not work properly in production mode.
Should I make an adjustment for this?

**Comment by rchl** [comment]
I don't know, you are not explaining what is happening.

But `rootRedirect` might need to be a full URL.

**Comment by fahamidev** [comment]
@rchl Okay. i explain about it.

### Project description
Our `Nuxtjs` project is a full dynamic. I mean we have multi domain project that each domain has own data, languages and locales.
when domain entered on the browser, **settings data** received from back-end that contains ( locales, defaultLocale, ... ) and the **problem is here**. Now after that if URL doesn't contain any locale (ex: `domain.com/`)  Nuxtjs have to redirect to the `defaultLocale` that received from **settings data** ( ex: if `defaultLocale='ar'` domain should redirect automatically to `domain.com/ar`    ) But now it always redirect to `domain.com/en`.

**What should I do to solve it?**

**Comment by rchl** [comment]
I think that `nuxt-i18n` is not currently equipped to handle that kind of usage. Some things are defined at build time (like `defaultLocale`) and used in the code so even if you update `i18n.defaultLocale`, it will use the one set at build time.

In some cases, we might be able to change the code so that it's more dynamic, but I'm not sure if we could make it fully dynamic.

I'd need minimal reproduction repo (or codesandbox) to see what exactly is a problem in your case and be able to look more closely at what would need to change.

**Comment by fahamidev** [comment]
This is the first part of the project where the information is received link settings
> codesandbox
[Link is here](https://codesandbox.io/s/dry-wave-b63m1?file=/pages/index.vue)

Thank you for your help.

**Comment by rchl** [comment]
Does this work as you would expect: https://codesandbox.io/s/nostalgic-thunder-yer1j ?

I've just changed store code to set data hardcoded data rather than getting it from external service.

Also, you are still doing this: `app.i18n.locale === "/fr"`. `locale` is a code, it doesn't and shouldn't contain any slashes.

**Comment by fahamidev** [comment]
I change `app.i18n.locale === "/fr"` to `app.i18n.locale === "fr"` and build project. But my code still doesn't work properly. Because when it builds. `app.i18n.locale` is always sent `en`

In part of my code in [codesandbox](https://codesandbox.io/s/dry-wave-b63m1?file=/store/index.js) 
```
const whatIsLocaleInRootUrl = app.i18n.locale;
// whatIsLocaleInRootUrl => 'en'
if (!hasLocale || app.i18n.locale === "fr") {
   return redirect(........);
}
```

**Comment by rchl** [comment]
How are you building for production. Are you running on a node server (yarn build && yarn start) or generating static files (yarn generate)?

**Comment by fahamidev** [comment]
@rchl 
> How are you building for production? Are you running on a node server (nuxt build && nuxt start) or generating static files (nuxt generate)?

I am running on a node server (nuxt build && nuxt start).
`Localhost:3000` is used when I run nuxt start and then when the domain is called, the **port 3000** is called by **reverse proxy**
I do **not** use generate static file 
I don't use generate static file and so all JS files run in real time

**Comment by rchl** [comment]
Then it works for me with the sandbox you've linked above. You need to investigate this yourself as I can't reproduce, I'm afraid.

I don't have any reverse proxy setup though, maybe that's what makes the difference.

I suggest you log all request headers from `nuxtServerInit` and check if that gives any clue.

**Comment by fahamidev** [comment]
I'm looking for request headers.
Do you think it is possible to change the configuration of the `nuxt-i18n` package through the [Runtime Config](https://nuxtjs.org/guide/runtime-config) provided in the new version of Nuxtjs(2.13.x)?

**Comment by rchl** [comment]
It makes sense to investigate supporting Runtime Config in the module but I'd prefer a separate feature request for that.

**Comment by edwm101** [comment]
Hi @fahamidev just take a look at these documents 
https://i18n.nuxtjs.org/different-domains/
Hope you find a solution 💯
