### ISSUE TITLE
trailingSlash does not play nice with nuxtI18n: false

### ISSUE THREAD

**Issue by miteyema** [nuxt-community/i18n-module#787]
### Version
nuxt-i18n: 6.13.1
nuxt: 2.13.3

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt-i18n configuration
Please see `trailingSlash` in https://github.com/miteyema/nuxt-i18n-demo/blob/prod/nuxt.config.js
Please see `nuxtI18n: false` in https://github.com/miteyema/nuxt-i18n-demo/blob/prod/pages/privacy.vue

### Reproduction Link
https://github.com/miteyema/nuxt-i18n-demo

### Steps to reproduce
Navigate directly using the browser location bar to https://nuxt-i18n-demo.netlify.app/privacy

### What is Expected?
The page should be shown

### What is actually happening?
Endless redirects, thus not showing the correct page
When using dev tools and look at the logs, I see
`[vue-router] Route with name 'privacy___en' does not exist (repeated 30 times)`

### Extra info
If you go to https://nuxt-i18n-demo.netlify.app and use the privacy link to navigate to that page, it will work.
However, directly going to that page using browser location bar does not work.
This can also be seen in the build output in `dist/` when using `npm run build && npm run export` that `privacy/index.html` is not correctly generated...

Maybe this is related with issue https://github.com/nuxt-community/nuxt-i18n/issues/717 ?

**Comment by rchl** [comment]
Can you check in v6.13.2? I've fixed #798 there which sounds like the same issue.

I have trouble checking this one as all the static servers I'm trying (both `http-server` and `nuxt serve`) seem to automatically append trailing slash for `/private` path.

**Comment by rchl** [comment]
Note that if it's not possible to change static-servers behavior to not append the trailing slash then probably you would have to enable `generate.subFolders: false` in Nuxt config instead. But that can possibly come with another set of issues.

I think I can't fix the case when the server forces the trailing slash as it will render my redirect ineffective.

**Comment by miteyema** [comment]
@rchl Thanks for looking into my issue. I have updated the repo, but I still had the same problem.

I think you are right with the comment about the server forcing the trailing slash.
I changed it to `trailingSlash:true` and now everything works perfect, because Netlify forces the trailing slash on the server side, so I will just leave it like that.
