### ISSUE TITLE
is it possible to set the pages' nuxtI18n paths dynamically?

### ISSUE THREAD

**Issue by vesper8** [nuxt-community/i18n-module#791]
Hi there,

I'm currently porting a pretty large SPA which was built with vue-cli. It's multilingual and it had some nifty custom logic to handle url localization. The main benefit was that adding a new language was extremely easy, all you had to do was add the new locale (for example, 'es') and then populate the es.json with keys that matched all the existing routes

The way that nuxt-i18n currently handles localized routes is a bit off putting because you have to manually provide all the possible route translations somewhere, either in the nuxt.config.js or in each page component. This is extremely tedious and repetitive and the process of adding a new language is painful

A solution for me would be to allow the 

```
  nuxtI18n: {
    paths: {
      en: '/cities',
      fr: '/villes',
      es: '/ciudades',
    },
  },
```

To be generated dynamically. So just as an example if I could do something like this:

```
  asyncData({ app }) {
      const routeName = 'cities';

      app.$i18n.locales.forEach(locale => {
        nuxtI18n.paths[locale] = app.$i18n.t(`JSON.ROUTE_${routeName}`, locale)
      });
  },
```

I know this probably doesn't work in `asyncData` since it needs to be available when the routes.json generation happens. The point is, I'm looking for a way to generate this in a way that isn't tedious and repetitive and requires localized strings that are already available inside the en.json, fr.json, etc.json. Worse case scenario I'd be willing to create a little script that generates a localized-routes.json which can then be read or inserted inside the nuxt.config.js. I guess doing this step manually (generating a large blob of json with a custom loop and then inserting it manually inside the nuxt.config.js is the best thing I can think of right now. But I wish there was a less hacky way

If anyone has had the same problem and has an elegant solution I'd love to hear it!

Thanks

**Comment by flozero** [comment]
Currently the static solution for me its not working on component page level. It's only working on nuxt.config.js config...

+1 for this feature

**Comment by rchl** [comment]
@vesper8 Maybe have a look at https://i18n.nuxtjs.org/lang-switcher.html#dynamic-route-parameters

This approach requires that your routes are dynamic (named `_slug` or some such) rather than having static routes and generating them up-front.
