### ISSUE TITLE
langDir does not support absolute path

### ISSUE THREAD

**Issue by padinko** [nuxt-community/i18n-module#792]
### Version
nuxt-i18n: 6.13.1
nuxt: 2.13.3

#### [mode](https://nuxtjs.org/api/configuration-mode):
 - [x] universal
 - [] spa

### Nuxt-i18n configuration
```js
const { resolve } = require('path');
...
        ['nuxt-i18n', {
            lazy: true
            langDir: resolve(__dirname, 'lang'),
        }]
```
-->

### Steps to reproduce
I am trying to use lazy load on windows, but setting langDir to some diroctory with full path it will generate `options.js`:
```js
...
export const langDir = 'C:\web\work\zeoshop\client\lang'
...
```

### What is Expected?
backslash should be prefixed:
```js
...
export const langDir = 'C:\\web\\work\\zeoshop\\client\\lang'
...
```

### What is actually happening?
```
ERROR  in ./.nuxt/nuxt-i18n/options.js

Syntax Error: Unterminated string constant (9:23)

   7 | export const strategy = 'prefix_except_default'
   8 | export const lazy = true
>  9 | export const langDir = 'C:\web\work\zeoshop\client\lang\'
```

## edit
or probably i do something bad, because it is forcing `'~/<%= options.langDir %>'`.. what is `~` directory? why is it forced?

## edit 2
we have translable translation in admin area, so probably locale's `file` should be `http://...` ? to load newest translations every time by http/https protocol? but this is change request not bug (like this issue)

**Comment by rchl** [comment]
`langDir` should be relative to [srcDir](https://nuxtjs.org/api/configuration-srcdir).

I suppose this can be improved to work with absolute paths too.

**Comment by padinko** [comment]
yeah.. but we removed `~` alias to srcDir (in build.extend), we only use `@`.. because `~` is very buggy in less and importing node_modules styles (less have `~` alias to node_modules, and we want to use it).. 
so yeah langDir should be JSON.stringify (for prefixes backslash)
and maybe not forcing to `~/...` but use path.resolve with srcDir?

**Comment by kgrosvenor** [comment]
@padinko don't you think you are over complicating it?, please see this example for how you can get it working. 

```
i18n: {
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected'
    },
    locales: [
      {
        code: 'en-GB',
        file: 'en-GB.json',
        moment: 'en'
      },
      {
        code: 'en-CA',
        file: 'en-CA.json',
        moment: 'en'
      },
      {
        code: 'fr-CA',
        file: 'fr-CA.json',
        moment: 'fr'
      },
      {
        code: 'en-SA',
        file: 'en-SA.json',
        moment: 'en'
      },
      {
        code: 'en-IE',
        file: 'en-IE.json',
        moment: 'en'
      },
      {
        code: 'hi-IN',
        file: 'hi-IN.json',
        moment: 'in'
      },
      {
        code: 'en-IN',
        file: 'en-IN.json',
        moment: 'en'
      }
    ],
    defaultLocale: 'en-GB',
    lazy: true,
    langDir: 'locales/',
    vueI18n: {
      fallbackLocale: 'en-GB',
      messages: {
        'en-GB': require('./locales/en-GB'),
        'fr-CA': require('./locales/fr-CA'),
        'en-CA': require('./locales/en-CA'),
        'en-IE': require('./locales/en-IE'),
        'en-SA': require('./locales/en-SA'),
        'hi-IN': require('./locales/hi-IN'),
        'en-IN': require('./locales/en-IN')
      }
    }
  },
```

**Comment by padinko** [comment]
we have translations editable in admin area.. so that JSONs are changeable in runtime, so we need to load actual json on every load (have some small cache time on server)
so I need to get around building translations messages with webpack

**Comment by kgrosvenor** [comment]
@padinko  i see, that makes sense for the usecase then!

**Comment by rchl** [comment]
> we have translable translation in admin area, so probably locale's `file` should be `http://...` ? to load newest translations every time by http/https protocol? but this is change request not bug (like this issue)

No, it can't and won't support `http://...`. Instead, you can assign a javascript file to the `file` property, that exports a function and you can have any custom logic you want there, including loading translations from a remote endpoint. See https://i18n.nuxtjs.org/lazy-load-translations.html for an example.

I'm treating this bug as being about supporting absolute paths in `langDir` and nothing more.

**Comment by rchl** [comment]
Should have been fixed a couple versions ago.
