### ISSUE TITLE
using from translation routing excluded route and defaultLocale together leads to reload loop on this page(s)

### ISSUE THREAD

**Issue by violoncelloCH** [nuxt-community/i18n-module#798]
### Version
nuxt-i18n: 6.13.1
nuxt: 2.13.0

#### [mode](https://nuxtjs.org/api/configuration-mode): 
 - [x] universal
 - [ ] spa

### Nuxt-i18n configuration
<details>
<summary>configuration</summary>

```
i18n: {
    locales: [
      {
        code: 'en',
        iso: 'en-GB',
        isCatchallLocale: true
      },
      {
        code: 'de',
        iso: 'de-CH'
      }
    ],
    defaultLocale: 'en',
    strategy: 'prefix',
    vueI18n: {
      fallbackLocale: 'en'
    },
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_redirected'
    },
    parsePages: false,
    pages: {
      admin: false
    }
}
```
</details>

### Reproduction Link
let me know and I'll commit my test setup for this...
EDIT: https://git.violoncello.ch/websites/repro-nuxti18n-798

### Steps to reproduce
- create a `admin.vue` file in `/pages` with some demo content
- access `/admin` -> gets redirected to `/en/admin/` which is not found
- access `/admin/` -> leads to a reload loop (browser is reloading the page constantly)

### What is Expected?
If I didn't get something wrong, I should be able to set `defaultLocale` as recommended and use it together with `parsePages: false, pages: { admin: false } }`

### What is actually happening?
the route which is from localization routing excluded isn't accessible (as described above)

**Comment by rchl** [comment]
Can you repro this in dev mode or with generated static page or...?

**Comment by violoncelloCH** [comment]
Thanks for your answer @rchl !
I can actually reproduce it in both dev mode and generated static page (served over `nuxt serve`).
While playing around with it a little more I noticed, that the behavior described above depends on `router: { trailingSlash: true }`. If I unset this/set it to false, then accessing `/admin` or `/admin/` both lead to the same reload loop.
Let me know if I can provide anything more to help investigating this!

**Comment by rchl** [comment]
You might have to provide a repo that reproduces. I can't be wasting time trying to reproduce with no complete information being provided.

The redirect loop might be fixable but the:
> access /admin -> gets redirected to /en/admin/ which is not found

case I'm not sure as it might need #641 to be solved first.

**Comment by violoncelloCH** [comment]
okay, I see - here you go: https://git.violoncello.ch/websites/repro-nuxti18n-798
clone over https: https://git.violoncello.ch/websites/repro-nuxti18n-798.git

I created the reproduction with `router: { trailingSlash: true }` and realized that the second case (redirection to /en/admin/) only happens in dev mode.

**Comment by rchl** [comment]
Thanks, that reproduces. The `target: 'static'` was really the root trigger. It reproduces with and without `trailingSlash`.

I'll fix the redirect loop with #812.

**Comment by rchl** [comment]
Released in [v6.13.2](https://github.com/nuxt-community/i18n-module/releases/tag/v6.13.2)

**Comment by violoncelloCH** [comment]
wow, that was fast! :tada: thank you very much!
I guess the release will be available soon via npm...

**Comment by rchl** [comment]
Published now.

(Thanks for pointing it out that it's not released. I've actually released it but at different name accidentally. :)).
