### ISSUE TITLE
migrate to nuxtjs org

### ISSUE THREAD

**Issue by pi0** [nuxt-community/i18n-module#800]
- [x] Setup i18n.nuxtjs.org domain
- [x] Setup netlify
- [x] Rename repository to `i18n-module`
- [x] Set redirect for github pages (nuxt-community.github.io/nuxt-i18n)
- [x] Update base URL and netlify redirects
- [x] Publish `@nuxtjs/i18n`
- [ ] Depprecate `nuxt-i18n` package

Deployment is published at https://nuxt-i18n.netlify.app. Domain alias https://i18n.nuxtjs.org is pending for dns cache invalidation (TTL: ~1hour)

**Comment by rchl** [comment]
Publishing as `@nuxtjs/i18n` would mean that users would have to update the reference to the module in their modules array right?

Or it's possible to publish with different name while using same directory name in node_modules?

Because if the directory name changes then it's a breaking change.

**Comment by pi0** [comment]
@rchl Breaking change is probably introducing a behaviour or configuration change in same semver-major of same package. Deprecating one package, we can start `@nuxt/i18n` from 1.x and advice users do the migration (no force or break existing projects)

**Comment by rchl** [comment]
Yes, that makes sense.
It's just I'm not sure it's the best time for that now as there are some pending improvements that users are pushing for.
I think I'd prefer to release those under the old name and then make the switch (because once I make the switch it doesn't make sense to maintain the old one anymore).

**Comment by pi0** [comment]
Anytime you would prefer @rchl :) Issue is to keep track of progress only

**Comment by yvanavermaet** [comment]
Unsure if it's a problem on my end, but I'm noticing the following:
1. the old domain doesn't redirect to the new one (the checkbox in the first post shows it's done, but doesn't work here)
2. the new domain (https://i18n.nuxtjs.org/) does not load properly. All resources throw a 404. The Netlify url does work.

Apologies if I misinterpreted the checkboxes of the first posts claiming the above should already work.

Good luck with the further rollout of these changes!

**Comment by rchl** [comment]
> 2\. the new domain ([i18n.nuxtjs.org](https://i18n.nuxtjs.org/)) does not load properly. All resources throw a 404.

That works here so not sure what's the issue for you. Maybe have a look at network requests using browser inspector?

> 1. the old domain doesn't redirect to the new one

Yes. That's unfortunate but it doesn't seem fixable while keeping all old repo links working.

**Comment by yvanavermaet** [comment]
All assets throw a 404 using wifi (laptop and phone), but return a 200 when on 4G (phone). So will probably be a DNS issue with my (wifi-)provider.

In regards to the old domain not redirecting to the new one: I found the docs via Google and when they didn't work I went to the readme and clicked on "check out the docs" and got the same result. I see that you've updated the link in the readme to reflect the new url, so nothing further from me :-)

Best of luck

**Comment by pi0** [comment]
Sorry for inconveniences due to docs migration. Last TTL i checked was 1 hour but sometimes providers automatically increase. It may take few more days to fully propagate. meanwhile we can use netlify link nuxt-i18n.netlify.app 😊

**Comment by divine** [comment]
FYI Search input returns links to https://nuxt-community.github.io/nuxt-i18n/ which is 404 not found.

**Comment by rchl** [comment]
Yes. That's unfortunate but it doesn't seem fixable while keeping all old repo links working at the same time.

**Comment by Igloczek** [comment]
I'm also facing 404 on https://i18n.nuxtjs.org/, because it points to not existing Github Pages. I'm using 1.1.1.1 Cloudflare DNS.

**Comment by rchl** [comment]
@Igloczek should be fixed now.

**Comment by Igloczek** [comment]
Indeed it works, thanks 🙇

**Comment by Igloczek** [comment]
But, there is one more thing that doesn't work correctly, the search results links, because all URLs starts with `/nuxt-i18n/`.
Is: https://i18n.nuxtjs.org/nuxt-i18n/lazy-load-translations.html#lazy-load-translations
Should be: https://i18n.nuxtjs.org/lazy-load-translations.html#lazy-load-translations

**Comment by rchl** [comment]
@s-pace Hey. Do you know what needs to be done to fix the Algolia index to point to new URLs?

The module has moved from https://github.com/nuxt-community/nuxt-i18n/ to https://github.com/nuxt-community/i18n-module/ and the search index still uses old URLs.

**Comment by s-pace** [comment]
👋 @rchl 

Config updated an the Algolia index is not correctly built with the https://i18n.nuxtjs.org/ URLs

**Comment by rchl** [comment]
@s-pace Thank you :)

**Comment by rchl** [comment]
The name change and migration was handled in #1198.

Now also deprecated the `nuxt-i18n` package - https://www.npmjs.com/package/nuxt-i18n?activeTab=versions
