### ISSUE TITLE
How to trigger fallback to phrase instead of key?

### ISSUE THREAD

**Issue by uran1980** [nuxt-community/i18n-module#961]
Hi, folks.

Is it posible for keys that did not exists on locale fallback to default locale key.

For example: I have `en` as default locale and `ru` as other, the `en` locale key in `en-US.js` file.:
```
{
  "client_agreement": "Client agreement"
}
```

on `ru-RU.js` I have not this key.

By default behavior when I switch to `ru` locale, I see on site this:

```
client_agreement
```

But I want to see this instead:

```
Client agreement
```

Is it possible, Thanks.

**Comment by rchl** [comment]
```js
    i18n: {
        // ...
        vueI18n: {
            fallbackLocale: 'en',
        }
    }
```
